### ISSUE TITLE
Full GitHub Port + Update Remaining Assets

### ISSUE THREAD

**Issue by TheRealDannyyy** [WebCreationClub/alfred-botler#53]
I still have some assets on my Google Drive cloud that belong to the CC. Additionally a lot of these assets could be updated to a more modern design, based on the new Alfred assets by _skymen_.

**To-Do:**
- [x] Update remaining assets (forum; rules + more?)
- [x] Update + port forum topic as text file in GitHub
- [x] Port asset source files (PS5, Illustrator etc.)
